#! /usr/bin/python3

netids = [ None ] * 128
netids[0x00] = 'Private/experimental nodes'
netids[0x01] = 'Private/experimental nodes'
netids[0x02] = 'Actility'
netids[0x03] = 'Proximus'
netids[0x04] = 'Swisscom'
netids[0x05] = 'unassigned'
netids[0x06] = 'La Poste'
netids[0x07] = 'Bouygues Telecom'
netids[0x08] = 'Orbiwise'
netids[0x09] = 'SENET'
netids[0x0A] = 'KPN'
netids[0x0B] = 'EveryNet'
netids[0x0C] = 'unassigned'
netids[0x0D] = 'SK Telecom'
netids[0x0E] = 'SagemCom'
netids[0x0F] = 'Orange'
netids[0x10] = 'A2A Smart City'
netids[0x11] = 'TATA Communication'
netids[0x12] = 'Kerlink'
netids[0x13] = 'The Things Network'
netids[0x14] = 'DIGIMONDO GmbH'
netids[0x15] = 'Cisco Systems'
netids[0x16] = 'unassigned'
netids[0x17] = 'MultiTech Systems'
netids[0x18] = 'Loriot'
netids[0x19] = 'NNNCo'
netids[0x1A] = 'unassigned'
netids[0x1B] = 'TrackNet'
netids[0x1C] = 'Lar.Tech'
netids[0x1D] = 'unassigned'
netids[0x1E] = 'unassigned'
netids[0x1F] = 'Axatel  Italy'
netids[0x20] = 'Telent (Netzikon)'
netids[0x21] = 'unassigned'
netids[0x22] = 'Comcast'
netids[0x23] = 'Ventia'
netids[0x24] = 'Helium'
netids[0x25] = 'unassigned'
netids[0x26] = 'unassigned'
netids[0x27] = 'unassigned'
netids[0x28] = 'VADSLYFE'
netids[0x29] = 'unassigned'
netids[0x2A] = 'M2B Communications'
netids[0x2B] = 'ZTE'
netids[0x2C] = 'unassigned'
netids[0x2D] = 'unassigned'
netids[0x2E] = 'unassigned'
netids[0x2F] = 'unassigned'
netids[0x30] = 'SoftBank'
netids[0x31] = 'Inmarsat'
netids[0x32] = 'Gemalto'
netids[0x33] = 'Alibaba Iot BU'
netids[0x34] = 'ER-Telecom Holding'
netids[0x35] = 'Shenzhen Tencent Computer Systems Company Limited'
netids[0x36] = 'Netze BW GmbH'
netids[0x37] = 'Tektelic'
netids[0x38] = 'Charter Communicaton'

def mtype_to_str(m):
    if m == 0:
        return 'join request'
    if m == 1:
        return 'join accept'
    if m == 2:
        return 'unconfirmed data up'
    if m == 3:
        return 'unconfirmed data down'
    if m == 4:
        return 'confirmed data up'
    if m == 5:
        return 'confirmed data down'
    if m == 6:
        return 'RFU'
    if m == 7:
        return 'proprietary'

    return '???'
